### ISSUE TITLE
Awaiting a new release with support of MS-MPI

### ISSUE THREAD

**Issue by dsorokin** [rsmpi/rsmpi#67] opened 2019-03-30 17:50 UTC
Hi! Thank you for your excellent work! Today I could successfully install your library on macOS and Windows 10. Unfortunately, there was some trouble with Windows initially. Therefore, I would like to suggest to update the documentation so that it would be easier for others to install `rsmpi` on Windows. It seems there is a lack of documentation in the Internet.

So, I had to install clang+LLVM after MS-MPI, then I had to use the recent Git version of `rsmpi` instead of that one, which is currently known as release 0.5.4. The release has no support of MS-MPI. Finally, when creating a dependency on the cloned `rsmpi` repository, I had to reset the default features in `Cargo.toml` so that they would not use `libffi`, which I could not build with help of MSYS2. It seems that `libffi` has indeed some issues on Windows. Only then I could use `rsmpi` on Windows 10.

Thus, I am actually asking when are you going to make a new release with support of MS-MPI? Also I'm interesting in that how are you going to treat the mentioned Windows-only issue with default features? Probably, it could be documented in some way.

Thanks,
David Sorokin

**Comment by dsorokin** [comment] 2019-03-30 18:22
Also I have to add that I could build `rsmpi` using the MSVC toolchain only. When using the GNU toolchain, the compilation fails on Windows.

**Comment by AndrewGaspar** [comment] 2019-03-31 23:46
Could you share the error message you get when building with the GNU toolchain?

**Comment by AndrewGaspar** [comment] 2019-04-01 01:21
For the issues here:

I agree that we should put out a 0.5.5 release with the MS-MPI support. @bsteinb 

For the libffi issue, I've proposed making `user-operations`, which pulls in `libffi`, [a non-default feature](https://github.com/bsteinb/rsmpi/issues/56) for v0.6, which is allowed to have breaking changes from v0.5. For now, you can specify `default-features = false` in your project's Cargo.toml, or specify `--no-default-features` when building rsmpi directly.

For the build issue, at least for me, the issue appeared to be that bindgen doesn't supply the path to GNU's C standard library to libclang, so it can't find, for example, stdint.h. I explicitly specified the path to the header in the mpi-sys `build.rs`, and that seemed to fix it. Not quite sure how to solve this problem generally yet - will have to do more research.

**Comment by AndrewGaspar** [comment] 2019-04-01 02:28
After some investigation into my own build error on `-gnu`, I WAS able to build without any modifications when I removed a second path to `gcc.exe` I had in my PATH variable. I installed mingw via chocolatey, and that resulted in two paths being in my PATH variable:
* C:\ProgramData\chocolatey\bin
* C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin

When I removed "C:\ProgramData\chocolatey\bin", which I presume are essentially symlinks, that allowed libclang to identify the GNU installation, and it was then able to find the includes to use.

Perhaps you ran into a similar issue?

**Comment by dsorokin** [comment] 2019-04-01 04:17
It is very probable that my compilation issue can indeed be related to other installations that use MinGW, GCC, ld and some other applications. For example, I have Haskell Platform installed that also changes the Path environment variable. But I will be able to test this idea later only.

Below the error is provided as you requested.

By the way, this is not already related to the issue. I started using the `immediate_send` method. I had some trouble with the lifetime of the buffer. I have to keep the buffer somewhere so that I could finish the awaiting requests in the loop. Finally, I just inlined your definition of the `immediate_send` method and saved the internal buffer in a vector without hard lifetime requirements. Probably, it will work. I realize why the `immediate_send` function has such a lifetime bound for the buffer, but I want to say that it was unclear for me how to use it, for my buffer cannot live for so long as the request scope does, which is not true in my case. I send `Vec<u8>` asynchronously and do this frequently in the loop. This is just for your information.

```
C:\Docs\test-rsmpi\test01>rustup default stable-x86_64-pc-windows-gnu
info: using existing install for 'stable-x86_64-pc-windows-gnu'
info: default toolchain set to 'stable-x86_64-pc-windows-gnu'

  stable-x86_64-pc-windows-gnu unchanged - rustc 1.33.0 (2aa4c46cf 2019-02-28)


C:\Docs\test-rsmpi\test01>cargo clean

C:\Docs\test-rsmpi\test01>cargo build --release
   Compiling memchr v2.2.0
   Compiling winapi-build v0.1.1
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling libc v0.2.51
   Compiling winapi v0.3.6
   Compiling winapi v0.2.8
   Compiling lazy_static v1.3.0
   Compiling regex v0.2.11
   Compiling libloading v0.4.3
   Compiling glob v0.2.11
   Compiling ucd-util v0.1.3
   Compiling cfg-if v0.1.7
   Compiling utf8-ranges v1.0.2
   Compiling unicode-width v0.1.5
   Compiling strsim v0.7.0
   Compiling vec_map v0.8.1
   Compiling bindgen v0.31.3
   Compiling bitflags v1.0.4
   Compiling lazy_static v0.2.11
   Compiling peeking_take_while v0.1.2
   Compiling quote v0.3.15
   Compiling semver-parser v0.7.0
   Compiling cc v1.0.32
   Compiling build-probe-mpi v0.1.1 (C:\Docs\test-rsmpi\rsmpi\build-probe-mpi)
   Compiling custom_derive v0.1.7
   Compiling smallvec v0.6.9
   Compiling kernel32-sys v0.2.2
   Compiling thread_local v0.3.6
   Compiling log v0.4.6
   Compiling regex-syntax v0.5.6
   Compiling clang-sys v0.21.2
   Compiling textwrap v0.10.0
   Compiling semver v0.9.0
   Compiling conv v0.3.3
   Compiling log v0.3.9
   Compiling rustc_version v0.2.3
   Compiling memchr v1.0.2
   Compiling which v1.0.5
   Compiling aho-corasick v0.6.10
   Compiling mpi v0.5.4 (C:\Docs\test-rsmpi\rsmpi)
   Compiling atty v0.2.11
   Compiling nom v3.2.1
   Compiling clap v2.32.0
   Compiling cexpr v0.2.3
   Compiling env_logger v0.4.3
   Compiling mpi-sys v0.1.2 (C:\Docs\test-rsmpi\rsmpi\mpi-sys)
error: failed to run custom build command for `mpi-sys v0.1.2 (C:\Docs\test-rsmpi\rsmpi\mpi-sys)`
process didn't exit successfully: `C:\Docs\test-rsmpi\test01\target\release\build\mpi-sys-8357640798ee5d5c\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Include\\" "-Wall" "-Wextra" "-o" "C:\\Docs\\test-rsmpi\\test01\\target\\release\\build\\mpi-sys-f1d34301a470ce95\\out\\src\\rsmpi.o" "-c" "src/rsmpi.c"
exit code: 0
AR_x86_64-pc-windows-gnu = None
AR_x86_64_pc_windows_gnu = None
HOST_AR = None
AR = None
running: "ar" "crs" "C:\\Docs\\test-rsmpi\\test01\\target\\release\\build\\mpi-sys-f1d34301a470ce95\\out\\librsmpi.a" "C:\\Docs\\test-rsmpi\\test01\\target\\release\\build\\mpi-sys-f1d34301a470ce95\\out\\src\\rsmpi.o"
exit code: 0
cargo:rustc-link-lib=static=rsmpi
cargo:rustc-link-search=native=C:\Docs\test-rsmpi\test01\target\release\build\mpi-sys-f1d34301a470ce95\out
cargo:rustc-cfg=msmpi
cargo:rustc-link-search=native=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\
cargo:rustc-link-lib=msmpi

--- stderr
warning: argument unused during compilation: '-LC:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\' [-Wunused-command-line-argument]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vadefs.h:28:33: error: expected ';' after top level declarator
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:81:1: error: expected identifier
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:81:20: error: expected ';' after top level declarator
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:180:29: error: expected ';' after top level declarator
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:283:51: error: unknown type name 'uintptr_t'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:284:67: error: unknown type name 'uintptr_t'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:288:8: error: unknown type name 'uintptr_t'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:296:1: error: a parameter list without types is only allowed in a function definition
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:296:18: error: expected ';' after top level declarator
warning: argument unused during compilation: '-LC:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\' [-Wunused-command-line-argument], err: false
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vadefs.h:28:33: error: expected ';' after top level declarator, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:81:1: error: expected identifier, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:81:20: error: expected ';' after top level declarator, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:180:29: error: expected ';' after top level declarator, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:283:51: error: unknown type name 'uintptr_t', err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:284:67: error: unknown type name 'uintptr_t', err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:288:8: error: unknown type name 'uintptr_t', err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:296:1: error: a parameter list without types is only allowed in a function definition, err: true
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include\vcruntime.h:296:18: error: expected ';' after top level declarator, err: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by AndrewGaspar** [comment] 2019-04-01 04:55
This looks like something other than the issue I ran into. I'm not sure what to make of it yet. It's odd that libclang is following the `stdint.h` include to your MSVC installation, where it appears to be failing on an MSVC-specific type `__int64`, based on my reading of vadefs.h. This would seem to indicate to me that libclang at least is running in a "GCC" mode (not recognizing the MSVC-specific extension), but that clang is still erroneously looking at the MSVC includes.

Not sure how to debug this yet. What's your LLVM+Clang version?

**Comment by dsorokin** [comment] 2019-04-01 05:02
I did nothing specific. I just installed Clang+LLVM from their official site. Below the version is provided. Now it seems to me that Clang can be too specialized for the MSVC toolchain and that may be a cause. I might suggest that the compilation could go smooth if I installed Clang that ships with MSYS2.

```
>clang --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by AndrewGaspar** [comment] 2019-04-01 05:20
I'm building with `7.0.0` right now, but that's mainly because I haven't gotten around to updating - limited data cap right now, so can't install ATM. I wouldn't expect 8.0.0 to have any meaningful differences.

It _could_ be an issue if the default Rust target and default clang target don't match. Here's how I built:

```c++
GIT ~\Projects\rsmpi [master ≡]> & "C:\Program Files\LLVM\bin\clang.exe" --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
GIT ~\Projects\rsmpi [master ≡]> rustup toolchain list
stable-x86_64-pc-windows-msvc (default)
GIT ~\Projects\rsmpi [master ≡]> cargo clean -p mpi-sys --target x86_64-pc-windows-gnu
GIT ~\Projects\rsmpi [master ≡]> cargo build --target x86_64-pc-windows-gnu --no-default-features
   Compiling mpi-sys v0.1.2 (C:\Users\andre\Projects\rsmpi\mpi-sys)
   Compiling mpi v0.5.4 (C:\Users\andre\Projects\rsmpi)
    Finished dev [unoptimized + debuginfo] target(s) in 34.66s
```

However, based on my reading of [bindgen's code](https://github.com/rust-lang/rust-bindgen/blob/v0.31.2/src/ir/context.rs#L547), bindgen will pass the Rust target through to clang via `--target=`, even if you're using the default target. You could try to switch your default toolchain to `x86_64-pc-windows-msvc`, and then build for gnu using my method above. I would try to repro by switching toolchains to gnu myself, but I can't at this moment due to the data cap issue I mentioned before.

**Comment by dsorokin** [comment] 2019-04-01 05:30
Finally, I could build rsmpi by using the GNU toolchain both for Rust and Clang! I just switched to Clang that ships with MSYS32. Also I built successfully rsmpi before, when using the MSCV toolchain both for Rust and Clang simulateneously. I would suggest to document this.

Thank you!

**Comment by AndrewGaspar** [comment] 2019-04-01 05:38
Ok, good to know that there's an issue when the Rust toolchain and LLVM toolchain don't have the same default target. I suspect this is a bug somewhere in the stack (probably not rsmpi?), leaning towards bindgen. Will have to experiment some more. Note to self, a couple things to try:
* Install GNU Rust toolchain and GNU LLVM toolchain, experiment with mixing and matching these toolchains
* Update our bindgen, see if that resolves the issue.

**Comment by AndrewGaspar** [comment] 2019-04-03 04:13
Hm... I wasn't able to reproduce when mixing the rust GNU toolchain with the msvc clang, building both the default (which is gnu, for the GNU Rust toolchain), and explicitly building for the msvc and gnu targets.

**Comment by bsteinb** [comment] 2019-04-21 20:53
Yeah, I am in favor of preparing a new release as well, as it seems like the currently published version was broken by a dependency bumping its dependency versions. I am not certain whether we can at this point create a release from master and have it be compatible with `0.5`. In any case I would rather find a solution for #54 before making another release if it turns out that our entire interface should be changed in an incompatible way. I will give this some thought and report back before the end of the next week.

**Comment by jedbrown** [comment] 2022-08-05 16:22
This is tested in CI and part of the 0.6 release https://github.com/rsmpi/rsmpi/releases/tag/mpi-0.6.0 so I think we can close this issue. Feel free to reopen if needed.

**Closed by jedbrown** 2022-08-05 16:22 UTC
